In [1]:
#numpy
!pip install numpy

In [2]:
import numpy as np

In [8]:
x=np.random.randint(1,10)
x

9

In [9]:
x1=np.random.randint(1,10,size=4)#1D
x1

array([6, 1, 1, 2])

In [10]:
x2=np.random.randint(1,10,size=(4,2))#2D
x2

array([[9, 5],
       [7, 1],
       [7, 5],
       [1, 5]])

In [11]:
x3=np.random.randint(1,10,size=(4,2,1))#3D
x3

array([[[9],
        [4]],

       [[6],
        [6]],

       [[2],
        [9]],

       [[4],
        [9]]])

In [23]:
x2

array([[9, 5],
       [7, 1],
       [7, 5],
       [1, 5]])

In [33]:
x2[:1,:3]

array([[9, 5]])

In [34]:
x2[:2,:3]

array([[9, 5],
       [7, 1]])

In [56]:
x2[::-1,::-1]

array([[5, 1],
       [5, 7],
       [1, 7],
       [5, 9]])

In [36]:
x2[::-1,::-2]

array([[5],
       [5],
       [1],
       [5]])

In [39]:
x2[::-2,::-2]

array([[5],
       [1]])

In [41]:
original_array=[1,2,3,5,1,3,5,9]
copied_array=original_array.copy()
print(copied_array)

[1, 2, 3, 5, 1, 3, 5, 9]


In [43]:
original_array=np.array([[1,2,3],[4,5,6]])
copied_array=original_array.copy()
print(copied_array)

[[1 2 3]
 [4 5 6]]


In [53]:
original_array=np.array([[1,2,3],[4,5,6]])
copied_array=original_array.copy()
copied_array[0,2]=8
print("modified_array is:",copied_array)

modified_array is: [[1 2 8]
 [4 5 6]]


In [59]:
y=np.array([[1,2],[3,4],[5,6]])
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
y[2,1]

6

In [67]:
y[1:3]

array([[3, 4],
       [5, 6]])

In [68]:
y[0:2,0]

array([1, 3])

In [70]:
y.shape

(3, 2)

In [72]:
y.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr1=np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
#transpose
arr1=np.arange(9).reshape((3,3))
transposed_arr1=arr1.transpose()
transposed_arr1



array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [87]:
data1=np.array([[1,23,33,1],[1,23,44,3]])
data1


array([[ 1, 23, 33,  1],
       [ 1, 23, 44,  3]])

In [85]:
data2=np.array([[2,32,22,1],[7,22,22,2]])
data2

array([[ 2, 32, 22,  1],
       [ 7, 22, 22,  2]])

In [88]:
#concatenate
data1=np.array([[1,23,33,1],[1,23,44,3]])
data2=np.array([[2,32,22,1],[7,22,22,2]])
np.concatenate([data1,data2])


array([[ 1, 23, 33,  1],
       [ 1, 23, 44,  3],
       [ 2, 32, 22,  1],
       [ 7, 22, 22,  2]])

In [89]:
#hstack
stack1 = np.array([[99],[99]])
stack2 = np.array([[9,8,7],[6,5,4]])
np.hstack([stack2,stack1])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [92]:
#vstack
stack1 = np.array([[99,2,3],[9,3,9],[1,9,9]])
stack2 = np.array([[9,8,7],[6,5,4]])
np.vstack([stack2,stack1])



array([[ 9,  8,  7],
       [ 6,  5,  4],
       [99,  2,  3],
       [ 9,  3,  9],
       [ 1,  9,  9]])

In [99]:
#reverse
data = np.array([[2,9],[9,8],[7,6]])
reverse = np.flip(data,axis=1)
reverse

array([[9, 2],
       [8, 9],
       [6, 7]])

In [104]:
#max min and sum
data = np.array([[2,92],[19,8],[227,6]])
data.sum()
data.max()
data.min()

2

In [105]:
#doubt!
data = np.array([[2,0],[3,8],[1,6]])
data.min(axis=0)

array([1, 0])

In [117]:
#even_elements_splitting
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
sub_arrays = np.split(arr, 2)
sub_arrays


[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [119]:
#uneven_elements_splitting
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
sub_arrays = np.array_split(arr, 4)
sub_arrays


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [130]:
#hsplit and vsplit
x = [1,2,3,99,99,3,2,1]
yy=np.split(x,[2,4])
yy


[array([1, 2]), array([ 3, 99]), array([99,  3,  2,  1])]